=== perldoc-jp/jprp/project/perldocjp-faq.dtd
<!ENTITY % Inline "a|em|strong">
<!ENTITY % a.content "(#PCDATA|em|strong)">
<!ENTITY % URI "CDATA">

<!ELEMENT faqlist (section)+>
<!ELEMENT section (title, faq?)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT faq (part)+>
<!ELEMENT part (question,answer)+>
<!ELEMENT question (#PCDATA)>
<!ELEMENT answer (#PCDATA| %Inline; )+>

<!ELEMENT a %a.content;>
<!ATTLIST a
  href        %URI;          #IMPLIED
>

<!ELEMENT em (#PCDATA)>
<!ELEMENT strong (#PCDATA)>

=== perldoc-jp/jprp/web/faq/perldocjp-faq.xml
<?xml version="1.0" encoding="EUC-JP"?>
<!DOCTYPE faqlist SYSTEM "perldocjp-faq.dtd">
<faqlist>
<section>
<title>プロジェクトへの参加について</title>
<faq>
<part id="join_us">
<question>プロジェクトへ参加する方法は？</question>
<answer><a href="http://sourceforge.jp/projects/perldocjp/document/howtojoinus/ja/5/howtojoinus.html">perldocjpに参加するには</a>を読んでください。</answer>
</part>

<part id="english">
<question>英語はあまり得意ではないのですがプロジェクトに参加できますか？</question>
<answer>他の人が訳したものの査読（誤変換のチェックやわかりやすい日本語への修正）など様々な作業があるので是非参加してください。</answer>
</part>

<part id="cvs">
<question>CVS を使ったことないんですが参加できますか？</question>
<answer>よくわからない点があれば ML で気軽に質問すればよいので是非参加してください。</answer>
</part>

</faq>
</section>

<section>
<title>翻訳作業に関する質問</title>

<faq>
<part id="use_cvs">
<question>CVS の使い方がわからないのですがどうすればよいですか？</question>
<answer>まずは<a href="http://sourceforge.jp/projects/perldocjp/document/cvs_operation/ja/1/cvs_operation.html">CVSの操作</a>などを読んでください。
それでもわからない点があれば、ML で気軽に質問してください。
また、Microsoft Windows ユーザは<a href="http://sourceforge.jp/projects/perldocjp/document/cvs_wincvs/ja/3/cvs_wincvs.html">CVSの導入(WinCVS/Windows)</a>も用意されています。</answer>
</part>

<part id="no_use_cvs">
<question>CVS の使い方がやっぱりわからないのですが、プロジェクトへの参加は無理なのでしょうか？</question>
<answer>そんなことはありません。ML で代わりに CVS を使って登録してくれる人を探すことができます。だから気軽に参加してください。</answer>
</part>

<part id="cvs_repository">
<question>CVS リポジトリの構成は？</question>
<answer><a href="http://sourceforge.jp/projects/perldocjp/document/cvs_structure/ja/1/cvs_structure.html">CVSのディレクトリ構成</a>を読んでください。</answer>
</part>

<part id="how_to_translate">
<question>翻訳の流れはどのようになっていますか？</question>
<answer><a href="http://www.freeml.com/perldocjp/0000504">翻訳の流れ</a>を参考にしてください。</answer>
</part>

<part id="charset">
<question>文字コードは何を使えばいいですか？</question>
<answer>EUC-JP が使われているものも多いですが、UTF-8でも構いません。PODファイルの冒頭に「=encoding euc-jp」などと記述して、使用している文字コードを指定してください。適切に指定されていないと外部のツールやウェブサイトで適切に表示されない可能性があります。</answer>
</part>

<part id="get_pod">
<question>モジュールからの POD ファイルの抽出でどうやればよい？</question>
<answer>POD は「perldoc -u モジュール名」で抽出できるので、その結果をファイルに落とせばよいです。「perldoc -u モジュール名 > モジュール名.pod」などね。また、井上さんによる xpod.pl が <a href="http://www.freeml.com/perldocjp/0000160">Re: スクリプトから POD を取り出すプログラム</a>にあります。</answer>
</part>

<part id="pod_rule">
<question>PODのアンカー、句読点、カッコなどについてプロジェクトの規約はありますか？</question>
<answer>現状では作業者が好きな方を選択してください。将来的に統一が必要になったときに置換することにします。</answer>
</part>

<part id="english_to_japanese_table">
<question>訳語の対訳表はありますか？</question>
<answer>現在はありません。</answer>
</part>

<part id="some_translator">
<question>複数の人から同じドキュメントを登録したいという要求が発生した場合はどうすればいいですか？</question>
<answer>持ち主と主担当間で調整して一本化してください。（主担当が交代 or 増えるのはアリ）</answer>
</part>

<part id="ask_about_translation">
<question>モジュール作成者に翻訳物の公開の是非について問い合わせるべきですか？</question>
<answer>モジュールのライセンス次第です。Perl モジュールは Perl と同じライセンス（ Artistic License と GPL のデュアルライセンス）を適用されることが多く、それらのライセンスであれば翻訳物の公開はライセンス上許可されています。ですから、許可を得る必要はありません。ただ、翻訳したことを伝えることはやった方が望ましいです。</answer>
</part>

<part id="report_about_translation">
<question>では、モジュール作成者に報告する際にはどのように言えばよいですか？</question>
<answer><a href="http://www.freeml.com/perldocjp/0000485">Re: Kansai.pm - 3周年記念イベントまとめ</a>内に一例があります。参考にしてください。</answer>
</part>

<part id="ask_about_link">
<question>モジュール作成者からリンク先聞かれたらどうすればよいですか？</question>
<answer><a href="http://www.freeml.com/perldocjp/0000408">作者さんからリンク先って聞かれません？</a>からはじまるスレッドが参考になるでしょう。</answer>
</part>

<part id="insert_translators_info">
<question>翻訳したものに翻訳者の情報を入れる際にはどうすればいいですか？</question>
<answer>自由にいれてもらってよいです。一例を挙げると翻訳した POD ファイルの最後尾にでも「head1」として入れておくという方法があります。<a href="http://www.freeml.com/perldocjp/0000335">翻訳した人の連絡先って、どうしましょ？</a>からはじまるスレッドも参考になることでしょう。</answer>
</part>

</faq>

</section>

<section>
<title>プロジェクトへの要望</title>

<faq>
<part id="request_a_translation">
<question>翻訳して欲しいモジュールがあるんですけど、そのようなリクエストは受け付けてますか？</question>
<answer>リクエストは ML に流してください。運が良ければ誰かが訳してくれることでしょう。但し、誰も訳してくれなかったからといって怒らないでね。</answer>
</part>

<part id="find_some_typo">
<question>誤字を見つけたのですがどうすればよいですか？</question>
<answer>翻訳者に連絡するか、SourceForge JP の <a href="https://sourceforge.jp/tracker/?atid=589&amp;group_id=136&amp;func=browse">Bug Tracking System</a> で報告してください。
また、あなたが ML に参加しているのならば、ML 宛に報告してください。
さらに、あなたがプロジェクトメンバーであるならば、勝手に修正しておいてください。</answer>
</part>

</faq>

</section>

<section>
<title>成果物に関する質問</title>

<faq>
<part id="read_translated_documents">
<question>翻訳された文章はどこで閲覧できますか？</question>
<answer><a href="http://perldoc.jp/">perldoc.jp</a>や<a href="http://new.perldoc.jp/">new.perldoc.jp</a>を参照するか、<a href="http://cvs.sourceforge.jp/cgi-bin/viewcvs.cgi/perldocjp/">SourceForge JP上のCVSリポジトリ</a>を御利用下さい。</answer>
</part>

<part id="search_from_all_documents">
<question>翻訳された文章の全文検索は行えますか？</question>
<answer>2011年1月現在、全文検索の機能は提供されていません。Googleなどの検索エンジンでドメイン指定で <a href="http://perldoc.jp/">perldoc.jp</a> などを対象に検索してみてください。</answer>
</part>

</faq>

</section>


</faqlist>

=== perldoc-jp/jprp/project/perldocjp-faq.xml
<?xml version="1.0" encoding="EUC-JP"?>
<!DOCTYPE faqlist SYSTEM "perldocjp-faq.dtd">
<faqlist>
<section>
<title>プロジェクトへの参加について</title>
<faq>
<part>
<question>プロジェクトへ参加する方法は？</question>
<answer<a href="http://sourceforge.jp/projects/perldocjp/document/howtojoinus/ja/5/howtojoinus.html">perldocjpに参加するには</a>を読んでください。</answer>
</part>

<part>
<question>英語はあまり得意ではないのですがプロジェクトに参加できますか？</question>
<answer>他の人が訳したものの査読（誤変換のチェックやわかりやすい日本語への修正）など様々な作業があるので是非参加してください。</answer>
</part>

<part>
<question>CVS を使ったことないんですが参加できますか？</question>
<answer>よくわからない点があれば ML で気軽に質問すればよいので是非参加してください。</answer>
</part>

</faq>
</section>

<section>
<title>翻訳作業に関する質問</title>

<faq>
<part>
<question>CVS の使い方がわからないのですがどうすればよいですか？</question>
<answer>まずは<a href="http://sourceforge.jp/projects/perldocjp/document/cvs_operation/ja/1/cvs_operation.html">CVSの操作</a>などを読んでください。
それでもわからない点があれば、ML で気軽に質問してください。
また、Microsoft WIndows ユーザは<a href="http://sourceforge.jp/projects/perldocjp/document/cvs_wincvs/ja/3/cvs_wincvs.html">CVSの導入(WinCVS/Windows)</a>も用意されています。</answer>
</part>

<part>
<question>CVS の使い方がやっぱりわからないのですが、プロジェクトへの参加は無理なのでしょうか？</question>
<answer>そんなことはありません。ML で代わりに CVS を使って登録してくれる人を探すことができます。だから気軽に参加してください。</answer>
</part>

<part>
<question>CVS リポジトリの構成は？</question>
<answer><a href="http://sourceforge.jp/projects/perldocjp/document/cvs_structure/ja/1/cvs_structure.html">CVSのディレクトリ構成</a>を読んでください。</answer>
</part>

<part>
<question>文字コードは何を使えばいいですか？</question>
<answer>EUC-JP を使ってください。</answer>
</part>

<part>
<question>モジュールからの POD ファイルの抽出でどうやればよい？</question>
<answer>「perldoc -u モジュール名」で抽出できるので、その結果をファイルに落とせばよいです。「perldoc -u モジュール名 > モジュール名.pod」などね。また、井上さんによる xpod.pl が <a href="http://www.freeml.com/message/perldocjp@freeml.com/0000160">Re: スクリプトから POD を取り出すプログラム</a>にあります。</answer>
</part>

<part>
<question>PODのアンカー、句読点、カッコなどについてプロジェクトの規約はありますか？</question>
<answer>現状では作業者が好きな方を選択してください。将来的に統一が必要になったときに置換することにします。</answer>
</part>

<part>
<question>訳語の対訳表はありますか？</question>
<answer>現在はありません。</answer>
</part>

<part>
<question>複数の人から同じドキュメントを登録したいという要求が発生した場合はどうすればいいですか？</question>
<answer>持ち主と主担当間で調整して一本化してください。（主担当が交代 or 増えるのはアリ）</answer>
</part>

<part>
<question>モジュール作成者からリンク先聞かれたらどうすればよいですか？</question>
<answer><a href="http://www.freeml.com/message/perldocjp@freeml.com/0000408">作者さんからリンク先って聞かれません？</a>からはじまるスレッドが参考になるでしょう。</answer>
</part>

<part>
<question>翻訳したものに翻訳者の情報を入れる際にはどうすればいいですか？</question>
<answer>自由にいれてもらってよいです。一例を挙げると翻訳した POD ファイルの最後尾にでも「head1」として入れておくという方法があります。<a href="http://www.freeml.com/message/perldocjp@freeml.com/0000335">翻訳した人の連絡先って、どうしましょ？</a>からはじまるスレッドも参考になることでしょう。</answer>
</part>

</faq>

</section>

<section>
<title>プロジェクトへの要望</title>

<faq>
<part>
<question>翻訳して欲しいモジュールがあるんですけど、そのようなリクエストは受け付けてますか？</question>
<answer>リクエストは ML に流してください。運が良ければ誰かが訳してくれることでしょう。但し、誰も訳してくれなかったからといって起こらないでね。</answer>
</part>

<part>
<question>誤字を見つけたのですがどうすればよいですか？</question>
<answer>翻訳者に連絡するか、SourceForge JP の <a href="https://sourceforge.jp/tracker/?atid=589&amp;group_id=136&amp;func=browse">Bug Tracking System</a> で報告してください。
また、あなたが ML に参加しているのならば、ML 宛に報告してください。
さらに、あなたがプロジェクトメンバーであるならば、勝手に修正しておいてください。</answer>
</part>

</faq>

</section>

<section>
<title>成果物に関する質問</title>

<faq>
<part>
<question>翻訳された文章はどこで閲覧できますか？</question>
<answer><a href="http://perldoc.jp/">perldoc.jp</a>を参照するか、<a href="http://cvs.sourceforge.jp/cgi-bin/viewcvs.cgi/perldocjp/">SourceForge JP上のCVSリポジトリ</a>を御利用下さい。</answer>
</part>

<question>翻訳された文章の全文検索は行えますか？</question>
<answer><a href="http://www.cpan.jp/">CPAN.jp</a>を御参照下さい。また、このサイトは、perldocjp以外に、翻訳された文章を既に公開している他サイトを検索対象としています。</answer>
</part>

</faq>

</section>


</faqlist>
